stages:
-   lint
-   deploy

variables:
    TWINE_USERNAME: __token__
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.pip

cache:
    paths:
    -   $CI_PROJECT_DIR/.pip
    key: $CI_PROJECT_ID

lint-code:
    stage: lint
    image: borchero/pylint
    script:
    -   pip install -e .
    -   pylint pycave
    except:
    -   tags

upload-to-pypi:
    stage: deploy
    image: borchero/twine
    script:
    -   envsubst < setup.py > setup.final.py
    -   mv setup.final.py setup.py
    -   python setup.py sdist bdist_wheel
    -   twine upload dist/*
    only:
    -   tags
