version: 2.1

jobs:
    lint-code:
        docker:
        -   image: borchero/pycave:$CIRCLE_BRANCH
        steps:
        -   checkout
        -   run: pylint pycave

    deploy-to-pypi:
        docker:
        -   image: borchero/pycave:$CIRCLE_BRANCH
        steps:
        -   checkout
        -   run: python setup.py sdist bdist_wheel
        -   run: twine upload dist/*

workflows:
    version: 2
    ci-workflow:
        jobs:
        -   lint-code

    cd-workflow:
        jobs:
        -   deploy-to-pypi:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
