version: 2.1

jobs:
    lint-code:
        docker:
        -   image: borchero/pycave:latest
        steps:
        -   checkout
        -   run: pylint pycave

    deploy-to-pypi:
        docker:
        -   image: borchero/pycave:latest
        steps:
        -   checkout
        -   run: python setup.py sdist bdist_wheel
        -   run: twine upload dist/*

    generate-docs:
        docker:
        -   image: borchero/pycave:latest
        steps:
        -   checkout
        -   run: |
                sleep 5
                pip install pycave==$CIRCLE_TAG || pip install pycave==$CIRCLE_TAG
        -   run: |
                cd docs
                sphinx-build . build
                cd ..
                mkdir -p ../.docs/.circleci
                cp -r docs/build/* ../.docs/
                cp -r .circleci/* ../.docs/.circleci/
                cd ../.docs

                mv _static static
                for file in ./**/*.html; do
                    sed -i 's/_static/static/g' $file
                done

                git init
                git config user.name "circleci"
                git config user.email "noreply@borchero.com"
                git add .
                git commit -m "Update Sphinx Docs"
                git push --force $CIRCLE_REPOSITORY_URL master:gh-pages

workflows:
    version: 2
    ci-workflow:
        jobs:
        -   lint-code:
                filters:
                    branches:
                        ignore: gh-pages

    cd-workflow:
        jobs:
        -   deploy-to-pypi:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
        -   generate-docs:
                requires: 
                -   deploy-to-pypi
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
