name: Deploy Package
on:
  - release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/borchero/poetry:1.1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Wheel
        run: poetry build
      - name: Publish to PyPi
        run: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
