name: Check Code Style
on:
  - push
  - pull_request
defaults:
  run:
    shell: bash

jobs:
  run-black:
    name: Black
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && source $HOME/.poetry/env
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run Black
        run: black --check pycave

  run-isort:
    name: Isort
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && source $HOME/.poetry/env
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run isort
        run: isort --check pycave

  run-pylint:
    name: Pylint
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && source $HOME/.poetry/env
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run Pylint
        run: pylint pycave

  run-pyright:
    name: Pyright
    runs-on: ubuntu-latest
    container:
      image: node:16.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run PyRight
        run: npm run lint
