name: Run Tests
on:
  - push
  - pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/borchero/poetry:1.1.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Library
        run: poetry install --no-interaction --no-ansi
      - name: Run Pytest
        run: pytest tests
